spring:
  application:
    name: retail-api
  data:
    cassandra:
      keyspace-name: product
      contact-points: localhost
      port: 9042
      schema-action: NONE
      consistency-level: ONE

  cloud:
    circuit:
      breaker:
        enabled: true

server:
  port: 8080

api:
  product:
    url: https://redsky.target.com/v2/pdp/tcin/{productId}?excludes=taxonomy,price,promotion,bulk_ship,rating_and_review_reviews,rating_and_review_statistics,question_answer_statistics

debug:
  false

security:
  basic:
    enabled: false

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
